/** Stored in SQLite as plain strings (see TZ / product conventions). */
export const ATTENDANCE_STATUS = {
  PRESENT: "PRESENT",
  LATE: "LATE",
  UNEXCUSED_ABSENCE: "UNEXCUSED_ABSENCE",
  SICK_PENDING: "SICK_PENDING",
  SICK_CONFIRMED: "SICK_CONFIRMED",
  ACADEMIC_ABSENCE: "ACADEMIC_ABSENCE",
  CLASS_DISRUPTION: "CLASS_DISRUPTION",
} as const;
